import Link from "next/link"
import {
  RiArrowRightSLine,
  RiFolderMusicLine,
  RiSparkling2Line,
  RiTimeLine,
  RiUploadCloud2Line,
} from "@remixicon/react"
import { Button } from "@/components/ui/button"
import { requireSession } from "@/lib/auth-guard"
import { listOwnedRecordings } from "@/lib/recordings/store"

function duration(seconds: number) {
  return `${Math.floor(seconds / 60)}:${(seconds % 60).toString().padStart(2, "0")}`
}

export default async function HomePage() {
  const session = await requireSession()
  const recs = await listOwnedRecordings(session.user.id)

  return (
    <div className="mx-auto max-w-6xl px-4 py-6 lg:px-6">
      <div className="mb-4 flex items-end justify-between gap-4">
        <div>
          <h1 className="text-xl font-semibold tracking-[-0.02em]">Library</h1>
          <p className="mt-0.5 text-sm text-muted-foreground">
            {recs.length} {recs.length === 1 ? "recording" : "recordings"}
          </p>
        </div>
        <Button asChild size="sm" className="sm:hidden">
          <Link href="/upload">
            <RiUploadCloud2Line data-icon="inline-start" />
            Upload
          </Link>
        </Button>
      </div>

      {recs.length === 0 ? (
        <div className="grid min-h-64 place-items-center rounded-xl border border-dashed p-6 text-center">
          <div>
            <RiFolderMusicLine className="mx-auto mb-3 size-7 text-muted-foreground" />
            <p className="font-medium">No recordings yet</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Record from the Mac app or upload an audio file.
            </p>
          </div>
        </div>
      ) : (
        <div className="overflow-hidden rounded-xl border bg-card">
          {recs.map((rec) => (
            <Link
              key={rec.id}
              href={`/recordings/${rec.id}`}
              className="group grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b px-3 py-3 transition-colors last:border-b-0 hover:bg-muted/45 sm:px-4"
            >
              <span className="grid size-8 place-items-center rounded-lg bg-muted text-muted-foreground">
                <RiFolderMusicLine className="size-4" />
              </span>
              <span className="min-w-0">
                <span className="flex items-center gap-1.5">
                  <span className="truncate text-sm font-medium">
                    {rec.title}
                  </span>
                  {rec.titleOrigin === "generated" && (
                    <RiSparkling2Line
                      aria-label="Generated by Engram AI"
                      className="size-3.5 shrink-0 text-primary"
                    />
                  )}
                </span>
                <span className="mt-0.5 flex flex-wrap items-center gap-x-2 text-xs text-muted-foreground">
                  <span>
                    {new Date(rec.createdAt).toLocaleDateString("en-GB", {
                      day: "2-digit",
                      month: "short",
                      year: "numeric",
                    })}
                  </span>
                  {rec.durationSeconds != null && (
                    <span className="inline-flex items-center gap-1 tabular-nums">
                      <RiTimeLine className="size-3" />
                      {duration(rec.durationSeconds)}
                    </span>
                  )}
                  <span className="capitalize">{rec.source}</span>
                </span>
              </span>
              <span className="flex items-center gap-2">
                <span className="hidden rounded-full bg-muted px-2 py-0.5 text-[11px] text-muted-foreground capitalize sm:inline">
                  {rec.status.replaceAll("_", " ")}
                </span>
                <RiArrowRightSLine className="size-4 text-muted-foreground transition-transform group-hover:translate-x-0.5" />
              </span>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
